# Minimal compose for gpu setup
# To bring up network in gpu mode use:
# docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d --wait

---

services:
  compute:
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
