- name: Provision Bacalhau Compute Instance
  remote_user: ubuntu
  # Ability to override host, useful to running playbook in local mode
  hosts: "{{ target_hosts | default('tag_Type_compute_only') }}"
  vars:
    nvidia_distribution: ubuntu2004
    ipfs_version: "0.18.0"
    ipfs_path: "/opt/ipfs"
    gpu: true
    go_version: 1.20.3
    bacalhau_version: "v1.0.3"
    bacalhau_node_type: "compute"
    ipfs_connect: /ip4/127.0.0.1/tcp/5001
    owner: labdao
  tasks:
    # Must provide limit flag to ensure running against correct environment
    - fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

    - name: Run common tasks
      ansible.builtin.include_tasks: tasks/common_tasks.yaml

    # Docker
    - name: Install Docker
      ansible.builtin.include_tasks: tasks/install_docker_tasks.yaml

    # GPU
    - name: Install tools and binaries for GPU support
      ansible.builtin.include_tasks: tasks/install_gpu_tasks.yaml
      when: gpu

    # Ensure handlers are restarted before continuing
    - name: flush handlers
      ansible.builtin.meta: flush_handlers

        # # Install IPFS
        # - name: Install IPFS
        #   ansible.builtin.include_tasks: tasks/install_ipfs_tasks.yaml
        #   tags: ipfs_install

    # Run Bacalhau agent
    - name: Run Baclahau agent
      ansible.builtin.include_tasks: tasks/install_bacalhau_tasks.yaml
      tags: bacalhau

  handlers:
    - name: Restart docker
      become: true
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Restart Bacalhau
      become: true
      ansible.builtin.service:
        name: compute
        state: restarted
        enabled: true
