basic_settings:
  experiment_name: test12345
  binder_length: 50
  pdb: 4N5T
  pdb_chain: A
  num_designs: 1
advanced_settings:
  pdb_start_residue: 50
  pdb_end_residue: 100
  hotspot: ''
  min_binder_length: null
  max_binder_length: null
  use_beta_model: false
expert_settings:
  RFDiffusion_Binder:
    contigs_override: ''
    # the contigs_override completely overrules all other contig related settings. Make sure it is '' if you do not want to overwrite settings.
    iterations: 50
    visual: none
  RFDiffusion_Symmetry:
    symmetry: none
    order: 1
    chains: ''
    add_potential: true
  ProteinMPNN:
    num_seqs: 16
    rm_aa: C
    mpnn_sampling_temp: 0.1
    use_solubleMPNN: true
    initial_guess: true
  Alphafold:
    use_multimer: false
    num_recycles: 3
